name: Deploy to Production

on:
  push:
    tags:
      - '*' # Triggers on version tags like 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/,Dockerfile,nginx.conf"
          target: "/home/${{ secrets.SERVER_USER }}/vinko-mlacic-web"
          strip_components: 0

      - name: Build Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/vinko-mlacic-web
            docker build -t vinko-mlacic-web:${{ github.ref_name }} .
            docker tag vinko-mlacic-web:${{ github.ref_name }} vinko-mlacic-web:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Production (Recreates the docker containers)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/reverse-proxy
            docker compose up -d
